"""Add parsed fields to inbound_emails

Revision ID: ac7d469eb461
Revises: 11eea6c63b85
Create Date: 2025-08-27 10:15:46.581440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7d469eb461'
down_revision: Union[str, Sequence[str], None] = '11eea6c63b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbound_emails', sa.Column('parsed_address', sa.String(), nullable=True))
    op.add_column('inbound_emails', sa.Column('parsed_datetime', sa.String(), nullable=True))
    op.add_column('inbound_emails', sa.Column('parsed_county', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbound_emails', 'parsed_county')
    op.drop_column('inbound_emails', 'parsed_datetime')
    op.drop_column('inbound_emails', 'parsed_address')
    # ### end Alembic commands ###
